services:
  - type: web
	name: django-app
	env: python
	buildCommand: pip install -r requirements.txt
	startCommand: python manage.py runserver 0.0.0.0:8000
	envVars:
	  - key: DATABASE_URL
		fromDatabase:
		  name: django-db
		  property: connectionString
	healthCheckPath: /
  - type: pserv
	name: django-db
	env: mysql
	databaseName: mydatabase
	version: 8